# Generated by Django 3.0.2 on 2020-02-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200201_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Add Your Content')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created Time')),
                ('modified_at', models.DateTimeField(verbose_name='Modified Time')),
            ],
        ),
    ]
